# -*- coding: utf-8 -*-
"""assignment_20_AM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PxLhbmL8Xd61TZoZE82cHkUIW4Yqd1Jx
"""

lst = [4, 7, 2, 9, 1, 5]

max_val = lst[0]
min_val = lst[0]

for i in lst:
    if i > max_val:
        max_val = i
    if i < min_val:
        min_val = i

print("Maximum:", max_val)
print("Minimum:", min_val)

lst = [1, 2, 2, 3, 1, 4, 2]

freq = {}

for i in lst:
    if i in freq:
        freq[i] = freq[i] + 1
    else:
        freq[i] = 1

print("Frequency:", freq)

num = 123
rev = 0

while num > 0:
    digit = num % 10
    rev = rev * 10 + digit
    num = num // 10

print("Reversed number:", rev)

num = 121
original = num
rev = 0

while num > 0:
    digit = num % 10
    rev = rev * 10 + digit
    num = num // 10

if original == rev:
    print("Palindrome")
else:
    print("Not Palindrome")

tuple_list = [("a", 1), ("b", 2), ("c", 3)]

result = {}

for item in tuple_list:
    key = item[0]
    value = item[1]
    result[key] = value

print("Dictionary:", result)

d = {"a": 10, "b": 25, "c": 15}

max_key = None
max_val = None

for key in d:
    if max_val is None or d[key] > max_val:
        max_val = d[key]
        max_key = key

print("Highest value key:", max_key)

def calc(*args):
    total = 0
    count = 0

    for i in args:
        total = total + i
        count = count + 1

    avg = total / count
    return total, avg


print(calc(10, 20, 30))

def top_student(**kwargs):
    max_name = None
    max_marks = None

    for name in kwargs:
        if max_marks is None or kwargs[name] > max_marks:
            max_marks = kwargs[name]
            max_name = name

    return max_name, max_marks


print(top_student(Aman=85, Ravi=92, Sita=88))

class Vector:
    def __init__(self, values):
        self.values = values


    def __add__(self, other):
        result = []
        for i in range(len(self.values)):
            result.append(self.values[i] + other.values[i])
        return Vector(tuple(result))


    def __sub__(self, other):
        result = []
        for i in range(len(self.values)):
            result.append(self.values[i] - other.values[i])
        return Vector(tuple(result))


    def __mul__(self, scalar):
        result = []
        for i in range(len(self.values)):
            result.append(self.values[i] * scalar)
        return Vector(tuple(result))


    def __repr__(self):
        return f"Vector{self.values}"

v1 = Vector((1, 2, 3))
v2 = Vector((4, 5, 6))

print("Vector 1:", v1)
print("Vector 2:", v2)

print("Addition:", v1 + v2)
print("Subtraction:", v1 - v2)
print("Scalar Multiplication:", v1 * 3)

class Student:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks


    def calculate_grade(self):
        if self.marks >= 80:
            return "A"
        elif self.marks >= 60:
            return "B"
        else:
            return "C"

    def __str__(self):
        grade = self.calculate_grade()
        return f"Name: {self.name}, Marks: {self.marks}, Grade: {grade}"


s1 = Student("Himkar", 85)
print(s1)

class Number:
    def __init__(self, value):
        self.value = value

    def __str__(self):
        return f"Value is {self.value}"

    def __add__(self, other):
        return Number(self.value + other.value)


# Test
n1 = Number(10)
n2 = Number(20)

print(n1)          # uses __str__
print(n1 + n2)     # uses __add__